defmodule Replicant.Telemetry do
  @moduledoc """
  Value-free `:telemetry.span/3` wrapper. Owns the metadata AND measurement contracts —
  the single enforcement point for "no row values in telemetry" (Critical Rule 1). Each
  permitted key carries a closed value-SHAPE contract, not just key-closure: an LSN is a
  non-negative integer, a count is a non-negative integer, a duration is a non-negative
  integer, a boolean is a boolean, a table/slot name is a string or a value-free nil
  absent marker, and an error class is an atom. A key that is off-list, or on-list with
  the WRONG shape (a row value smuggled in
  as a string where an LSN belongs), raises rather than shipping a value downstream. The
  shape-violation error renders only an allowed atom key and the value's TYPE — never the
  value itself. Off-list errors elide the rejected keys as well, because map keys can be
  attacker-controlled terms. The guard therefore cannot leak the bytes it exists to keep
  out. Mirrors `arcadic`'s allowlist pattern.
  """

  # Metadata (the 3rd arg): key => value-shape contract. Derived from every emission site.
  #   * :lsn             — `commit_lsn`: a non-negative integer WAL position, OR nil. The
  #     checkpoint-store `:read` event reports `commit_lsn: nil` on a fresh slot (no stored
  #     checkpoint yet); nil is value-free (an "absent" marker, not row bytes), so it is
  #     admitted while strings and non-nil atoms are still rejected.
  #   * :non_neg_integer — counts (`change_count`, `byte_size`, `attempt`, `max_retries`)
  #     and durations in ms (`lag_ms`, `duration`).
  #   * :boolean         — `transactional`.
  #   * :nullable_name   — a table/slot string or nil. Schema-change sites can carry a
  #     nil table name, and library mode has no replication slot; nil is a value-free
  #     absent marker, not row bytes.
  #   * :atom            — value-free error/`kind` classes (`reason`, `error_class`,
  #     `kind`); these are compile-time atoms, never `String.to_atom` of row bytes.
  @meta_shapes %{
    commit_lsn: :lsn,
    change_count: :non_neg_integer,
    byte_size: :non_neg_integer,
    lag_ms: :non_neg_integer,
    duration: :non_neg_integer,
    attempt: :non_neg_integer,
    max_retries: :non_neg_integer,
    transactional: :boolean,
    table: :nullable_name,
    slot_name: :nullable_name,
    reason: :atom,
    error_class: :atom,
    kind: :atom
  }

  # Measurements (the 2nd arg): key => value-shape contract.
  #   * :non_neg_integer — `duration` (ms), `byte_size`, `change_count`.
  #   * :integer         — `lag` is SIGNED: `received - max(cp, floor) - spilled` is
  #     WAL-byte arithmetic that can go negative, so a non-negative guard would
  #     over-reject a legitimate emission.
  @measurement_shapes %{
    duration: :non_neg_integer,
    lag: :integer,
    byte_size: :non_neg_integer,
    change_count: :non_neg_integer
  }

  @allowed_meta_keys Map.keys(@meta_shapes)
  @allowed_measurement_keys Map.keys(@measurement_shapes)

  @doc "The permitted span/event metadata keys."
  @spec allowed_meta_keys() :: [atom()]
  def allowed_meta_keys, do: @allowed_meta_keys

  @doc "The permitted event measurement keys."
  @spec allowed_measurement_keys() :: [atom()]
  def allowed_measurement_keys, do: @allowed_measurement_keys

  @doc """
  Wrap `fun` in a `[:replicant, op]` span, validating BOTH the start metadata and the returned
  stop metadata against the value-free contract (`validate!/1` raises on an off-list key or a
  wrong-shape value). `fun` must return `{result, stop_meta}`. The span's own measurements
  (`monotonic_time`/`duration`) are generated by `:telemetry` and are not user-supplied.
  """
  @spec span(atom(), map(), (-> {term(), map()})) :: term()
  def span(op, start_meta, fun) when is_atom(op) and is_map(start_meta) and is_function(fun, 0) do
    :telemetry.span([:replicant, op], validate!(start_meta), fn ->
      {result, stop_meta} = fun.()
      {result, validate!(Map.merge(start_meta, stop_meta))}
    end)
  end

  @doc """
  Emit a value-free telemetry event. BOTH `measurements` and `meta` are validated against their
  closed key + value-shape contracts (`validate!/1` and `validate_measurements!/1` raise on an
  off-list key or a wrong-shape value), so no row/column value can reach a telemetry consumer.
  """
  @spec event([atom(), ...], map(), map()) :: :ok
  def event(name, measurements, meta)
      when is_list(name) and is_map(measurements) and is_map(meta) do
    :telemetry.execute(name, validate_measurements!(measurements), validate!(meta))
  end

  @doc false
  @spec validate!(map()) :: map()
  def validate!(meta) when is_map(meta) do
    validate_keys!(meta, @allowed_meta_keys, "metadata")
    validate_shapes!(meta, @meta_shapes, "metadata")
    meta
  end

  @doc false
  @spec validate_measurements!(map()) :: map()
  def validate_measurements!(measurements) when is_map(measurements) do
    validate_keys!(measurements, @allowed_measurement_keys, "measurement")
    validate_shapes!(measurements, @measurement_shapes, "measurement")
    measurements
  end

  # Key-closure: every key must be on the allowlist. The rejected keys are arbitrary map
  # terms, so the error elides them and reports only a safe count plus the static allowlist.
  defp validate_keys!(map, allowed, kind) do
    case Map.keys(map) -- allowed do
      [] ->
        :ok

      bad ->
        raise ArgumentError,
              "telemetry #{kind} contains #{length(bad)} key(s) not in the value-free allowlist " <>
                "#{inspect(allowed)} (no row values / column values in telemetry)"
    end
  end

  # Value-shape: every value must match its key's contract. On a mismatch the error renders
  # only the key and the value's TYPE NAME — NEVER the value (which could be row/secret bytes).
  defp validate_shapes!(map, shapes, kind) do
    Enum.each(map, fn {key, value} ->
      shape = Map.fetch!(shapes, key)

      shape_ok?(shape, value) ||
        raise(
          ArgumentError,
          "telemetry #{kind} key #{inspect(key)} must be #{describe(shape)} " <>
            "(got type: #{type_name(value)}; value elided — no row/column values in telemetry)"
        )
    end)
  end

  defp shape_ok?(:lsn, value), do: is_nil(value) or (is_integer(value) and value >= 0)
  defp shape_ok?(:non_neg_integer, value), do: is_integer(value) and value >= 0
  defp shape_ok?(:integer, value), do: is_integer(value)
  defp shape_ok?(:boolean, value), do: is_boolean(value)
  defp shape_ok?(:nullable_name, value), do: is_binary(value) or is_nil(value)
  defp shape_ok?(:atom, value), do: is_atom(value)

  defp describe(:lsn), do: "a non-negative integer or nil"
  defp describe(:non_neg_integer), do: "a non-negative integer"
  defp describe(:integer), do: "an integer"
  defp describe(:boolean), do: "a boolean"
  defp describe(:nullable_name), do: "a string or nil"
  defp describe(:atom), do: "an atom"

  # Type name only — the value is NEVER rendered (Critical Rule 1). `is_boolean` precedes
  # `is_atom` because booleans are atoms.
  defp type_name(value) when is_binary(value), do: "binary"
  defp type_name(value) when is_integer(value), do: "integer"
  defp type_name(value) when is_float(value), do: "float"
  defp type_name(value) when is_boolean(value), do: "boolean"
  defp type_name(value) when is_atom(value), do: "atom"
  defp type_name(value) when is_list(value), do: "list"
  defp type_name(value) when is_map(value), do: "map"
  defp type_name(value) when is_tuple(value), do: "tuple"
  defp type_name(_value), do: "term"
end
